version: 1
module_version: 1.0.0

tests:
  - name: System-assigned identity
    project_root: examples/system-assigned-identity

  # This test case is currently disabled because the destroy is failing when trying to delete
  # the KeyVault. It looks like it may be related to this issue: https://github.com/hashicorp/terraform-provider-azurerm/issues/19322
  # - name: Password authentication
  #   project_root: examples/password-authentication
